/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConductRouteImport } from './routes/_authenticated/conduct'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConductIndexRouteImport } from './routes/_authenticated/conduct.index'
import { Route as AuthenticatedConductEmployeeIdRouteImport } from './routes/_authenticated/conduct.$employeeId'
import { Route as AuthenticatedConductStoreStoreIdRouteImport } from './routes/_authenticated/conduct.store.$storeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConductRoute = AuthenticatedConductRouteImport.update({
  id: '/conduct',
  path: '/conduct',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConductIndexRoute =
  AuthenticatedConductIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConductRoute,
  } as any)
const AuthenticatedConductEmployeeIdRoute =
  AuthenticatedConductEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AuthenticatedConductRoute,
  } as any)
const AuthenticatedConductStoreStoreIdRoute =
  AuthenticatedConductStoreStoreIdRouteImport.update({
    id: '/store/$storeId',
    path: '/store/$storeId',
    getParentRoute: () => AuthenticatedConductRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conduct': typeof AuthenticatedConductRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/conduct/$employeeId': typeof AuthenticatedConductEmployeeIdRoute
  '/conduct/': typeof AuthenticatedConductIndexRoute
  '/conduct/store/$storeId': typeof AuthenticatedConductStoreStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/conduct/$employeeId': typeof AuthenticatedConductEmployeeIdRoute
  '/conduct': typeof AuthenticatedConductIndexRoute
  '/conduct/store/$storeId': typeof AuthenticatedConductStoreStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/conduct': typeof AuthenticatedConductRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/conduct/$employeeId': typeof AuthenticatedConductEmployeeIdRoute
  '/_authenticated/conduct/': typeof AuthenticatedConductIndexRoute
  '/_authenticated/conduct/store/$storeId': typeof AuthenticatedConductStoreStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/conduct'
    | '/dashboard'
    | '/conduct/$employeeId'
    | '/conduct/'
    | '/conduct/store/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/conduct/$employeeId'
    | '/conduct'
    | '/conduct/store/$storeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/conduct'
    | '/_authenticated/dashboard'
    | '/_authenticated/conduct/$employeeId'
    | '/_authenticated/conduct/'
    | '/_authenticated/conduct/store/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conduct': {
      id: '/_authenticated/conduct'
      path: '/conduct'
      fullPath: '/conduct'
      preLoaderRoute: typeof AuthenticatedConductRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conduct/': {
      id: '/_authenticated/conduct/'
      path: '/'
      fullPath: '/conduct/'
      preLoaderRoute: typeof AuthenticatedConductIndexRouteImport
      parentRoute: typeof AuthenticatedConductRoute
    }
    '/_authenticated/conduct/$employeeId': {
      id: '/_authenticated/conduct/$employeeId'
      path: '/$employeeId'
      fullPath: '/conduct/$employeeId'
      preLoaderRoute: typeof AuthenticatedConductEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedConductRoute
    }
    '/_authenticated/conduct/store/$storeId': {
      id: '/_authenticated/conduct/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/conduct/store/$storeId'
      preLoaderRoute: typeof AuthenticatedConductStoreStoreIdRouteImport
      parentRoute: typeof AuthenticatedConductRoute
    }
  }
}

interface AuthenticatedConductRouteChildren {
  AuthenticatedConductEmployeeIdRoute: typeof AuthenticatedConductEmployeeIdRoute
  AuthenticatedConductIndexRoute: typeof AuthenticatedConductIndexRoute
  AuthenticatedConductStoreStoreIdRoute: typeof AuthenticatedConductStoreStoreIdRoute
}

const AuthenticatedConductRouteChildren: AuthenticatedConductRouteChildren = {
  AuthenticatedConductEmployeeIdRoute: AuthenticatedConductEmployeeIdRoute,
  AuthenticatedConductIndexRoute: AuthenticatedConductIndexRoute,
  AuthenticatedConductStoreStoreIdRoute: AuthenticatedConductStoreStoreIdRoute,
}

const AuthenticatedConductRouteWithChildren =
  AuthenticatedConductRoute._addFileChildren(AuthenticatedConductRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConductRoute: typeof AuthenticatedConductRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConductRoute: AuthenticatedConductRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
